-- MySQL Script generated by MySQL Workbench
-- Tue Mar  8 09:17:39 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema autopartage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema autopartage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `autopartage` DEFAULT CHARACTER SET utf8 ;
USE `autopartage` ;

-- -----------------------------------------------------
-- Table `autopartage`.`Loueur`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autopartage`.`Loueur` (
  `idClient` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Prenom` VARCHAR(45) NOT NULL,
  `Sexe` TINYINT NOT NULL,
  `Adresse` VARCHAR(45) NOT NULL,
  `AdresseMail` VARCHAR(45) NOT NULL,
  `Moyen de paiement` VARCHAR(45) NOT NULL,
  `Permis` VARCHAR(45) NOT NULL,
  `CarteIdentite` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idClient`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autopartage`.`Proprietaire`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autopartage`.`Proprietaire` (
  `idVoitures` INT NOT NULL AUTO_INCREMENT,
  `Nom` VARCHAR(45) NOT NULL,
  `Adresse mail` VARCHAR(45) NOT NULL,
  `MoyenDePaiement` VARCHAR(45) NOT NULL,
  `PapierDesVehicules` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idVoitures`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autopartage`.`GPS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autopartage`.`GPS` (
  `idGPS` INT NOT NULL AUTO_INCREMENT,
  `Latitude` VARCHAR(45) NOT NULL,
  `Longitude` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idGPS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autopartage`.`CAN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autopartage`.`CAN` (
  `idCAN` INT NOT NULL AUTO_INCREMENT,
  `carburant` VARCHAR(45) NOT NULL,
  `kilometrage` VARCHAR(45) NOT NULL,
  `GPS_idGPS` INT NOT NULL,
  PRIMARY KEY (`idCAN`, `GPS_idGPS`),
  INDEX `fk_CAN_GPS1_idx` (`GPS_idGPS` ASC),
  CONSTRAINT `fk_CAN_GPS1`
    FOREIGN KEY (`GPS_idGPS`)
    REFERENCES `autopartage`.`GPS` (`idGPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
PACK_KEYS = 0;


-- -----------------------------------------------------
-- Table `autopartage`.`Voiture`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autopartage`.`Voiture` (
  `idVoitures` INT NOT NULL AUTO_INCREMENT,
  `TypeDeVehicule` VARCHAR(45) NOT NULL,
  `Marque` VARCHAR(45) NOT NULL,
  `PrixDuModele` VARCHAR(45) NOT NULL,
  `DebutLocation` DATETIME NOT NULL,
  `FinLocation` DATETIME NOT NULL,
  `NomDuModele` DATETIME NOT NULL,
  `CoordonneGPS` VARCHAR(45) NOT NULL,
  `DateHeureGPS` DATETIME NOT NULL,
  `Proprietaire_idVoitures` INT NOT NULL,
  `GPS_idGPS` INT NOT NULL,
  `CAN_idCAN` INT NOT NULL,
  PRIMARY KEY (`idVoitures`, `Proprietaire_idVoitures`, `GPS_idGPS`, `CAN_idCAN`),
  INDEX `fk_Voiture_Proprietaire1_idx` (`Proprietaire_idVoitures` ASC),
  INDEX `fk_Voiture_GPS1_idx` (`GPS_idGPS` ASC),
  INDEX `fk_Voiture_CAN1_idx` (`CAN_idCAN` ASC),
  CONSTRAINT `fk_Voiture_Proprietaire1`
    FOREIGN KEY (`Proprietaire_idVoitures`)
    REFERENCES `autopartage`.`Proprietaire` (`idVoitures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voiture_GPS1`
    FOREIGN KEY (`GPS_idGPS`)
    REFERENCES `autopartage`.`GPS` (`idGPS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Voiture_CAN1`
    FOREIGN KEY (`CAN_idCAN`)
    REFERENCES `autopartage`.`CAN` (`idCAN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autopartage`.`Commande`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autopartage`.`Commande` (
  `idCommande` INT NOT NULL AUTO_INCREMENT,
  `VehiculeLoue` VARCHAR(45) NOT NULL,
  `Prix commande` VARCHAR(45) NOT NULL,
  `Loueur_idClient` INT NOT NULL,
  `Voiture_idVoitures` INT NOT NULL,
  `Voiture_Vendeur_idVoitures` INT NOT NULL,
  PRIMARY KEY (`idCommande`, `Loueur_idClient`, `Voiture_idVoitures`, `Voiture_Vendeur_idVoitures`),
  INDEX `fk_Commande_Loueur1_idx` (`Loueur_idClient` ASC) ,
  INDEX `fk_Commande_Voiture1_idx` (`Voiture_idVoitures` ASC, `Voiture_Vendeur_idVoitures` ASC) ,
  CONSTRAINT `fk_Commande_Loueur1`
    FOREIGN KEY (`Loueur_idClient`)
    REFERENCES `autopartage`.`Loueur` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Commande_Voiture1`
    FOREIGN KEY (`Voiture_idVoitures`)
    REFERENCES `autopartage`.`Voiture` (`idVoitures`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
